spring:
  application:
    name: data-application
  datasource:
    url: jdbc:postgresql://localhost:5432/zxc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 1004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/