spring:
  application:
    name: eureka-server
server:
  port: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost